image:
  - Visual Studio 2017

clone_folder: c:\projects\cpp-template

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..

build_script:
  - cmd: cmake --build . --config "Debug"
  - cmd: ctest -C "Debug" --output-on-failure
